### ISSUE TITLE
Integrate code analysis into .drone.yml

### ISSUE THREAD

**Issue by tlwt** [SCRATCh-ITEA3/demonstrator#1]
sonar_host and sonar_token are already set up ...
```
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
```
